### ISSUE TITLE
Encoding error?

### ISSUE THREAD

**Issue by frogpelt** [alexgreene/WikiQuiz#2]
I commented out lines 14, 27, 28 to see why it wouldn't work and I get this error.
 
`File "WikiQuiz-master/python/server.py", line 15, in get_quiz
    a = Article(article_name)
 File "WikiQuiz-master/python/Article.py", line 19, in __init__
    self.page.summary.encode('ascii', 'ignore'))
 File "WikiQuiz-master/python/Article.py", line 54, in generate_questions_for
    sec.replace(")", "("))[0::2])
TypeError: a bytes-like object is required, not 'str'`

I printed 'sec' and I do get text from the Wiki article but it fails on the first call to generate_questions_for()

**Comment by z1lc** [comment]
This is because `sec `is bytes when it comes back. I was able to resolve this by throwing in a `.decode("utf-8")`.
